CXX=clang++-3.8
CC=$(CXX)
CXXFLAGS=$(shell pkg-config --cflags opencv) -std=c++14 -g -DTEST=1
LDLIBS=$(shell pkg-config --libs opencv)

test3: test3.o
test: GlyphDetectPlugin.o

clean:
	rm -f test.o test

